
import React from 'react';
import Title from './componets/Title';
import Description from './componets/Description';
import Products from './componets/Products';



const productList = [
  { id: 1, title: '1º) Fiat Mobi - R$ 72.990', description: 'Versão de entrada: Like | Motor: 1.0 de quatro cilindros de 74 cv de potência e 9,7 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 9,6 km/l na cidade e 10,4 km/l na estrada com etanol - 13,5 km/l na cidade e 15 km/l na estrada com gasolina | Porta-malas: 235 litros', image: 'https://cdn.motor1.com/images/mgl/JO8elJ/s1/fiat-mobi-trekking-2023.jpg' },
  { id: 2, title: '2º) Renault Kwid - R$ 73.640', description: 'Versão de entrada: Zen | Motor: 1.0 tricilíndrico de 71 cv de potência e 10 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 10,8 km/l na cidade e 11 km/l na estrada com etanol - 15,3 km/l na cidade e 15,7 km/l na estrada com gasolina | Porta-malas: 290 litrosDescrição do Produto 2', image: 'https://s2-autoesporte.glbimg.com/ostbMNjyhm1Gu8A8Cuuizc2e8n0=/0x0:1400x788/888x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2022/6/a/1ZnCiuRLG6zLEqZgJULw/renault-kwid-outsider-12.jpg' },
  { id: 3, title: '3º) Citroën C3 - R$ 74.790', description: 'Versão de entrada: Live 1.0 MT | Motor: 1.0 Firefly de 75 cv de potência e 10,7 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 9,3 km/l na cidade e 10,5 km/l na estrada com etanol - 13 km/l na cidade e 14,6 km/l na estrada com gasolina | Porta-malas: 315 litros', image: 'https://cdn.motor1.com/images/mgl/KbBKGA/s3/comparativo-renault-kwid-x-citroen-c3-x-vw-polo-track.jpg' },
  { id: 4, title: '4º) Renault Stepway - R$ 84.470', description: 'Versão de entrada: Zen 1.0 | Motor: 1.0 de três cilindros de 82 cv de potência e 10,5 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 8,3 km/l na cidade e 8,5 km/l na estrada com etanol - 11,8 km/l na cidade e 12,1 km/l  na estrada com gasolina | Porta-malas: 320 litros', image: 'https://image1.mobiauto.com.br/images/api/images/v1.0/292089759/transform/fl_progressive,f_webp,q_80' },
  { id: 5, title: '5º) Fiat Argo - R$ 84.990', description: 'Versão de entrada: 1.0 | Motor: 1.0 Firefly de três cilindros de 75 cv de potência e 10,7 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 9,4 km/l na cidade e 10,2 km/l na estrada com etanol - 13,3 km/l na cidade e 14,7 km/l na estrada com gasolina | Porta-malas: 300 litros', image: 'https://cdn.motor1.com/images/mgl/7ZvOr6/s3/fiat-argo-2024.jpg' },
  { id: 6, title: '6º) Chevrolet Onix - R$ 86.150', description: 'Versão de entrada: 1.0 MT | Motor: 1.0 de três cilindros de 82 cv de potência e 10,6 kgfm de torque | Câmbio: manual de seis marchas | Consumo: 9,3 km/l na cidade e 11,4 km/l na estrada com etanol - 13,3 km/l na cidade e 16,5 km/l na estrada com gasolina | Porta-malas: 303 litros', image: 'https://quatrorodas.abril.com.br/wp-content/uploads/2023/04/ABRE-COMP-CITY-x-ONIX-1-e1680748097153.webp' },
  { id: 7, title: '7º) Hyundai HB20 - R$ 87.090', description: 'Versão de entrada: Sense Plus 1.0 | Motor: 1.0 Kappa 12V de três cilindros de 80 cv de potência e 10,2 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 9,6 km/l na cidade e 10,4 km/l na estrada com etanol - 13,5 km/l na cidade e 14,6 km/l na estrada com gasolina | Porta-malas: 300 litros', image: 'https://cdn.motor1.com/images/mgl/KbnopN/s1/comparativo-vw-polo-highline-vs.-chevrolet-onix-premier-vs.-hyundai-hb20-platinum-plus-vs.-honda-city-hatch-touring.jpg' },
  { id: 8, title: '8º) Volkswagen Polo - R$ 89.290', description: 'Versão de entrada: Track | Motor: 1.0 de três cilindros de 84 cv de potência e 10,4 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 9,4 km/l na cidade e 10,8 km/l na estrada com etanol - 13,7 km/l na cidade e 15,2 km/l na estrada com gasolina | Porta-malas: 300 litros', image: 'https://image1.mobiauto.com.br/images/api/images/v1.0/265303843/transform/fl_progressive,f_webp,q_70,w_592' },
  { id: 9, title: '9º) Peugeot 208 - R$ 91.990', description: 'Versão de entrada: Like 1.0 | Motor: 1.0 Firefly de 75 cv de potência e 10,7 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 9,6 km/l na cidade e 11,1 km/l na estrada com etanol - 13,3 km/l na cidade e 15,8 km/l na estrada com gasolina | Porta-malas: 265 litrosDescrição do Produto 8', image: 'https://cdn.motor1.com/images/mgl/xqpq7G/s1/peugeot-208-griffe-1.0-turbo-2024.jpg' },
  { id: 10, title: '10º) Fiat Cronos - R$ 93.990', description: 'Versão de entrada: Drive 1.0 | Motor: 1.0 Firefly de 75 cv de potência e 10,7 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 9,9 km/l na cidade e 11,4 km/l na estrada com etanol - 14 km/l na cidade e 16,1 km/l na estrada com gasolina | Porta-malas: 525 litros', image: 'https://fotos-jornaldocarro-estadao.nyc3.cdn.digitaloceanspaces.com/wp-content/uploads/2023/06/13164148/fiat-cronos-2023-jc1.jpg' },
  { id: 11, title: '11º) Hyundai HB20S - R$ 95.590', description: 'Versão de entrada: Comfort Plus 1.0 | Motor: 1.0 de três cilindros de 80 cv de potência e 10,2 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 9,4 km/l na cidade e 10,4 km/l na estrada com etanol - 13,2 km/l na cidade e 14,8 km/l na estrada com gasolina | Porta-malas: 475 litros', image: 'https://cdn.motor1.com/images/mgl/QeXRk9/s1/chevrolet-onix-plus-premier-2023-vs.-hyundai-hb20s-platinum-plus-2023.webp' },
  { id: 12, title: '12º) Renault Logan - R$ 97.010', description: 'Versão de entrada: Life | Motor: 1.0 flex de 82 cv de potência e 10,5 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 9,4 km/l na cidade e 10,2 km/l na estrada com etanol - 14 km/l na cidade e 14,9 km/l na estrada com gasolina | Porta-malas: 510 litros', image: 'https://image1.mobiauto.com.br/images/api/images/v1.0/274309209/transform/fl_progressive,f_webp,q_80' },
  { id: 13, title: '13º) Chevrolet Onix Plus - R$ 97.390', description: 'Versão de entrada: LT MT | Motor: 1.0 aspirado de 82 cv de potência e 10,6 kgfm de torque | Câmbio: manual de seis marchas | Consumo: 10,1 km/l na cidade e 12,4 km/l na estrada com etanol - 14,3 km/l na cidade e 17,5 km/l na estrada com gasolina | Porta-malas: 469 litros', image: 'https://cdn.appdealersites.com.br/saga/blog-2023/set23-2/Onix-Plus-2023%20%286%29.jpg' },
  { id: 14, title: '14º) Toyota Yaris Hatch - R$ 97.990', description: 'Versão de entrada: XL | Motor: 1.5 flex de 110 cv de potência e 14,9 kgfm de torque | Câmbio: CVT | Consumo: 8,9 km/l na cidade e 10 km/l na estrada com etanol - 12,2 na cidade e 13,8 km/l na estrada com gasolina | Porta-malas: 310 litros', image: 'https://garagem360.com.br/wp-content/uploads/2023/09/Toyota-Yaris-Hatch-2024-2.jpg' },
  { id: 15, title: '15º) Toyota Yaris Sedan - R$ 97.990', description: 'Versão de entrada: XL | Motor: 1.5 flex de 110 cv de potência e 14,9 kgfm de torque | Câmbio: CVT | Consumo: 9,2 km/l na cidade e 10,6 km/l na estrada com etanol - 12,7 km/l na cidade e 14,9 km/l na estrada com gasolina | Porta-malas: 473 litros', image: 'https://cdn.motor1.com/images/mgl/2NO6nM/s3/novo-toyota-yaris-2023.jpg' },
  { id: 16, title: '16º) Renault Kwid E-Tech - R$ 99.990', description: 'Versão de entrada: Única | Motor: elétrico de 65 cv de potência e 11,5 kgfm de torque | Câmbio: automático (frente e ré) | Autonomia: 185 km | Porta-malas: 290 litros', image: 'https://production.autoforce.com/uploads/picture/image/199567965/comprar-novo-kwid-e-tech-2024_33944c515e.jpg' },
  { id: 17, title: '17º) Volkswagen Saveiro - R$ 99.990', description: 'Versão de entrada: Robust CS | Motor: 1.6 de até 116 cv de potência e 16,1 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 7,9 km/l na cidade e 9,1 km/l na estrada com etanol - 11,5 km/l na cidade e 12,9 km/l na estrada com gasolina | Caçamba: 1.024 litros', image: 'https://www.webmotors.com.br/wp-content/uploads/2023/08/28062942/Volkswagen-Saveiro-2024-Youtube.webp' },
  { id: 18, title: '18º) Fiat Strada - R$ 103.490', description: 'Versão de entrada: Endurance 1.3 | Motor: 1.3 8V de 107 cv de potência e 14,2 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 8,9 km/l na cidade e 10,4 km/l na estrada com etanol - 12,9 km/l na cidade e 14,7 km/l na estrada com gasolina | Caçamba: 1.354 litros', image: 'https://opopular.com.br/image/policy%3A1.3055962%3A1691754759%2Fimage.jpg%3Ff%3D3x2' },
  { id: 19, title: '19º) Fiat Pulse - R$ 103.990', description: 'Versão de entrada: Drive 1.3 MT | Motor: 1.3 Firefly aspirado de 107 cv de potência e 13,7 kgfm de torque | Câmbio: manual de cinco marchas | Consumo: 9 km/l na cidade e 10,4 km/l na estrada com etanol - 12,5 km/l na cidade e 14,7 km/l na estrada com gasolina | Porta-malas: 370 litros', image: 'https://www.automaxfiat.com.br/wp-content/uploads/2024/04/fiat-pulse-s-design-2024-1.jpg' },
  { id: 20, title: '20º) Peugeot 2008 - R$ 109.990', description: 'Versão de entrada: Allure | Motor: 1.6 aspirado de 118 cv de potência e 16,1 kgfm de torque | Câmbio: automático de seis marchas | Consumo: 7,6 km/l na cidade e 8,6 km/l na estrada com etanol - 11 km/l na cidade e 12,4 km/l na estrada com gasolina | Porta-malas: 355 litros', image: 'https://cdn.appdealersites.com.br/saga/banners-blog-2023/out23-2/novo-peugeot-2008-2024.jpg' },
  

];

const App = () => (
  <div>
    <Title>20Cars</Title>
    <Description>Veja os 20 carros novos mais baratos do Brasil em 2024</Description>
    <Products products={productList} />
  </div>
);

export default App;
